repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: end-of-file-fixer
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
    - id: terraform_fmt
